### ISSUE TITLE
resize fotos

### ISSUE THREAD

**Issue by hannarosenfeld** [abflussengel/keywordediting#1]
open photographs in gimp and save them to the size that you will use.

**Comment by keywordbiomedical** [comment]
![About-us_2](https://user-images.githubusercontent.com/49872828/57866748-21911480-7800-11e9-93a5-0ddd7e6e3492.jpg)
![About_us_1](https://user-images.githubusercontent.com/49872828/57866749-21911480-7800-11e9-8fd0-74c928bd1dcd.jpg)
![Intro](https://user-images.githubusercontent.com/49872828/57866750-2229ab00-7800-11e9-8bbe-044c566e8cfa.jpg)

**Comment by keywordbiomedical** [comment]
cropped photos uploaded here

**Comment by hannarosenfeld** [comment]
done
