### ISSUE TITLE
replace diamond with something better

### ISSUE THREAD

**Issue by hannarosenfeld** [abflussengel/keywordediting#2]
fg typewriter or pen. google translate symbols.

**Comment by rizumu** [comment]
Check this out https://www.ikonate.com/

**Comment by keywordbiomedical** [comment]
just the empty circle without the diamond would be fine by me...

**Comment by rizumu** [comment]
@keywordbiomedical it looked a bit off empty, how about this keyboard? https://ecstatic-einstein-c33a86.netlify.com/en/
