### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by hannarosenfeld** [abflussengel/keywordediting#7]
Another question: what do I need to do to ensure that the site is GDPR compliant? Is that an issue, or only if I collect data from visitors to the site? And do I need to include a boilerplate privacy notice?

**Comment by keywordbiomedical** [comment]
Here's a word doc containing the privacy statement. I was thinking that it could be linked to from the contact form page?

[Privacy Statement.docx](https://github.com/abflussengel/keywordediting/files/3266858/Privacy.Statement.docx)
